WebAppFirst/Models/Orders.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int OrderID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<int> ShipVia { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress { get; set; }
        public string ShipCity { get; set; }
        public string ShipRegion { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual Shippers Shippers { get; set; }
    }
}

WebAppFirst/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppFirst.Models;
using PagedList;
using WebAppFirst.ViewModels;
using System.Runtime.Remoting.Messaging;

namespace WebAppFirst.Controllers
{
    public class OrdersController : Controller
    {
        private NorthwindEntities db = new NorthwindEntities();
        //Adding one test line to test the functionaliti of the gitignore file that was added.
        //One more line for testing purposes.
        // GET: Orders
        // TODO: Lisää toiminnallisuudet HOKS!!! Haettava tieto on Shippers taulussa ja Orders tauluissa Company Name! ShipName hämää.....
        public ActionResult OrderSummary()
        {
            var orderSummary = from o in db.Orders
                               join od in db.Order_Details on o.OrderID equals od.OrderID
                               join p in db.Products on od.ProductID equals p.ProductID
                               join c in db.Categories on p.CategoryID equals c.CategoryID
                               //where lause
                               //orderby lause
                               select new OrderSummaryData
                               {
                                   OrderID = (int)o.OrderID,
                                   CustomerID = o.CustomerID,
                                   EmployeeID = (int)o.EmployeeID,
                                   OrderDate = (DateTime)o.OrderDate,
                                   RequiredDate = (DateTime)o.RequiredDate,
                                   ShippedDate = (DateTime)o.ShippedDate,
                                   ShipVia = (int)o.ShipVia,
                                   Freight = (float)o.Freight,
                                   ShipName = o.ShipName,
                                   ShipAddress = o.ShipAddress,
                                   ShipCity = o.ShipCity,
                                   ShipRegion = o.ShipRegion,
                                   ShipPostalCode = o.ShipPostalCode,
                                   ShipCountry = o.ShipCountry,
                                   ProductID = p.ProductID,
                                   UnitPrice = (int)p.UnitPrice,
                                   Quantity = (int)od.Quantity,
                                   Discount = (float)od.Discount,
                                   ProductName = p.ProductName,
                                   SupplierID = (int)p.SupplierID,
                                   CategoryID = (int)c.CategoryID,
                                   QuantityPerUnit = p.QuantityPerUnit,
                                   UnitsInStock = (int)p.UnitsInStock,
                                   UnitsOnOrder = (int)p.UnitsOnOrder,
                                   ReorderLevel = (int)p.ReorderLevel,
                                   Discontinued = p.Discontinued,
                                   ImageLink = p.ImageLink,
                                   CategoryName = c.CategoryName,
                                   Description = c.Description,
                                   //Picture = (Image)c.Picture


                                   

                               };
            return View(orderSummary);
        }

        public ActionResult TilausOtsikot()
        {
            var orders = db.Orders.Include(o => o.Customers).Include(o => o.Employees).Include(o => o.Shippers);
            return View(orders.ToList()); 
        }

        public ActionResult _TilausRivit(int? orderid)
        {
            var orderRowsList = from od in db.Order_Details 
                               join p in db.Products on od.ProductID equals p.ProductID
                               join c in db.Categories on p.CategoryID equals c.CategoryID
                               where od.OrderID == orderid
                               //orderby lause
                               select new OrderRows
                               {
                                   OrderID = (int)od.OrderID,
                                   ProductID = p.ProductID,
                                   UnitPrice = (int)p.UnitPrice,
                                   Quantity = (int)od.Quantity,
                                   Discount = (float)od.Discount,
                                   ProductName = p.ProductName,
                                   SupplierID = (int)p.SupplierID,
                                   CategoryID = (int)c.CategoryID,
                                   QuantityPerUnit = p.QuantityPerUnit,
                                   UnitsInStock = (int)p.UnitsInStock,
                                   UnitsOnOrder = (int)p.UnitsOnOrder,
                                   ReorderLevel = (int)p.ReorderLevel,
                                   Discontinued = p.Discontinued,
                                   ImageLink = p.ImageLink,
                                   CategoryName = c.CategoryName,
                                   Description = c.Description,
                                   //Picture = (Image)c.Picture




                               };
            return PartialView(orderRowsList);
        }

        public ActionResult Index(string sortOrder,string searchString1, string currentFilter1, int? page, int? pagesize,string ShipperCategory, string currentShipperCategory)
        {   //Lajittelu
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CompanyNameSortParm = String.IsNullOrEmpty(sortOrder) ? "companyname_desc" : "";
            ViewBag.OrderDateSortParm = sortOrder == "OrderDate" ? "orderdate_desc" : "OrderDate";
            //Sivutus
            if (searchString1 != null)
            {
                page = 1;
            }
            else
            {
                searchString1 = currentFilter1;
            }

            ViewBag.currentFilter1 = searchString1;
            //Kategoriahaku muistiin
            if ((ShipperCategory != null) && (ShipperCategory != "0"))
            {
                page = 1;
            }
            else
            {
                ShipperCategory = currentShipperCategory;
            }

            ViewBag.currentShipperCategory = ShipperCategory;



            //Dropdownbox
            List<Shippers> lstShippers = new List<Shippers>();

            var shipperList = from cat in db.Shippers
                              select cat;

            Shippers tyhjaShippers = new Shippers();
            tyhjaShippers.ShipperID = 0;
            tyhjaShippers.CompanyName = "";
            tyhjaShippers.ShipperIDShipperName = "";
            lstShippers.Add(tyhjaShippers);

            foreach ( Shippers shipper in shipperList)
            {
                Shippers yksiShipper = new Shippers();
                yksiShipper.ShipperID = shipper.ShipperID;
                yksiShipper.CompanyName = shipper.CompanyName;
                yksiShipper.ShipperIDShipperName = shipper.ShipperID.ToString() + " - " + shipper.CompanyName;
                lstShippers.Add(yksiShipper);
            }
            ViewBag.ShipperID = new SelectList(lstShippers, "ShipperID", "ShipperIDShipperName", ShipperCategory);

            //Dropdownboxjatkuu...Tarvitaanko???
            //NorthwindEntities db = new NorthwindEntities();
            var rahtarit = from s in db.Shippers
                         select s;
            if (!String.IsNullOrEmpty(searchString1))
            {
                rahtarit = rahtarit.Where(s => s.CompanyName.Contains(searchString1));
            }
            if (!String.IsNullOrEmpty(ShipperCategory) && (ShipperCategory != "0")) 
            {
                int para = int.Parse(ShipperCategory);
                rahtarit = rahtarit.Where(p => p.ShipperID == para);
            }


            //Lajittelu
            var orders = from o in db.Orders.Include(o => o.Customers).Include(o => o.Employees).Include(o => o.Shippers)
                         select o;
            if (!String.IsNullOrEmpty(searchString1))
            {
                switch (sortOrder)
                {
                    case "companyname_desc":
                        orders = orders.Where(s =>s.Shippers.CompanyName.Contains(searchString1)).OrderByDescending(s => s.Shippers.CompanyName);
                        break;
                    case "OrderDate":
                        orders = orders.Where(s => s.Shippers.CompanyName.Contains(searchString1)).OrderBy(o => o.OrderDate); //Voi vaatia muutoksen s:ksi.
                        break;
                    case "OrderDate_desc":
                        orders = orders.Where(s => s.Shippers.CompanyName.Contains(searchString1)).OrderByDescending(o => o.OrderDate);
                        break;
                    default:
                        orders = orders.Where(s => s.Shippers.CompanyName.Contains(searchString1)).OrderBy(s => s.Shippers.CompanyName);
                        break;

                }
                orders = orders.Where(s => s.Shippers.CompanyName.Contains(searchString1));
            }
            else if (!String.IsNullOrEmpty(ShipperCategory) && (ShipperCategory != "0"))//Jos käytössä rajaus käytetään sitä ja lajitellaan.
            {
                int para = int.Parse(ShipperCategory);
                switch (sortOrder)
                {
                    case "companyname_desc":
                        orders = orders.Where(s => s.Shippers.ShipperID == para).OrderByDescending(s => s.Shippers.CompanyName);
                        break;
                    case "OrderDate":
                        orders = orders.Where(s => s.Shippers.ShipperID == para).OrderBy(o => o.OrderDate); //Voi vaatia muutoksen s:ksi.
                        break;
                    case "OrderDate_desc":

WebAppFirst/Views/Orders/Index.cshtml
@model PagedList.IPagedList<WebAppFirst.Models.Orders>
@using PagedList.Mvc;
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

@section scripts {
    <script type="text/javascript">
        //Pudotusvalikon jquery
        $("#singleSelectedShipperID").on("change", function () {
            var selValue = $("#singleSelectedShipperID").val();
            document.getElementById("ShipperCategory").value = selValue;
        });
        //JQuery, joka suoritetaan, kun klikataan getOrderId-luokan mukaista elementtiä
        $(function () {
            $(".getOrderId").click(function () {
                let orderId = $(this).data("orderid");
                console.log("Klikkasit tilausnumeroa: " + orderId);
                var url = "/Orders/_ModalEdit/?id=" + orderId;
                console.log(url);

                $("#orderEdit").append(" <b>Avataan tilauksen " + orderId + " muokkausikkuna...</b>");

                var $detailDivEdit = $("#orderEdit");
                $.get(url, function (data) {
                    $detailDivEdit.replaceWith(data);
                    $('#ModalOrderEdit').modal('show');
                });
            });
        });
        $(function () {
            $(".creNewOrder").click(function () {
                console.log("Klikkasit uuden tilauksen luontipainiketta: ");
                var url = "/Orders/_ModalCreate";
                console.log(url);

                $("#orderCreate").append(" <b>Avataan tilauksen luonti-ikkuna...</b>");

                var $detailDivCreate = $("#orderCreate");
                $.get(url, function (data) {
                    $detailDivCreate.replaceWith(data);
                    $('#ModalOrderCreate').modal('show');
                });
            });
        });

        $(function () {
            $(".delOrderId").click(function () {
                let orderId = $(this).data("orderid");
                console.log("Klikkasit poistettavaa tilausnumeroa: " + orderId);
                var url = "/Orders/_ModalDelete/?id=" + orderId;
                console.log(url);

                $("#orderDelete").append(" <b>Avataan tilauksen " + orderId + " poistoikkuna...</b>");

                var $detailDivDelete = $("#orderDelete");
                $.get(url, function (data) {
                    $detailDivDelete.replaceWith(data);
                    $('#ModalOrderDelete').modal('show');
                });
            });
        });

        function deleteOrder(deletedOrderId) {
            alert("Päätit poistaa tilauksen: " + deletedOrderId);
            var deleteurl = "/Orders/DeleteFromJQuery/?id=" + deletedOrderId;
            console.log(deleteurl);

            var ok = confirm("Haluatko varmasti poistaa asiakkaan " + deletedOrderId + "?");

            if (ok == true) {
                $.getJSON(deleteurl, null, function (status) {
                    if (status == true) {
                        alert("Tilaus on nyt poistettu!");
                        $('#ModalOrderDelete').modal('hide');
                        RefreshOrderList();
                    }
                    else {
                        alert("Poistaminen ei onnistunut, yritä uudelleen!");
                    }
                });
            }
        }

        function RefreshOrderList() {
            console.log("ennen ajaxia refresh");
            $.ajax({
                type: "GET",
                url: "/Orders/Index",
                success: function (result) {
                    console.log("resultti tuli " + result);
                    //$(document).replaceAll(result);  
                    document.open();
                    document.write(result);
                    document.close();
                }
            });
        }

    </script>
}




<h2>Tilaukset</h2>

<p>
    @Html.ActionLink("Tilausten yhteenveto", "OrderSummary")
</p>

<p>
    @Html.ActionLink("Tilausotsikot - Tilausrivit", "TilausOtsikot")
</p>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


<div id="orderEdit"></div>
<div id="orderDelete"></div>
<div id="orderCreate"></div>

@using (Html.BeginForm("Index", "Orders", FormMethod.Get))
{
    <div class="input-group">
        <p class="px-1">@Html.Label("Etsi nimellä: ")</p>
        <p class="px-1">@Html.TextBox("SearchString1", ViewBag.currentFilter1 as string, new { @class = "form-control" })</p>
        <p class="px-1">@Html.Label("Etsi Rahtarin perusteella: ")</p>
        <p class="px-1">@Html.Hidden("ShipperCategory", ViewBag.currentFilter1 as string, new { @id = "ShipperCategory", @class = "form-control" })</p>
        <p class="px-1">@Html.DropDownList("ShipperID", null, htmlAttributes: new { @id = "singleSelectedShipperID", @class = "form-control" }) </p>"
        <p class="px-1"><input type="submit" value="Search" class="form-control" /></p>
    </div>
}
<table class="table">
    <tr>
        <th><button class="creNewOrder fas fa-plus-square"></button></th>
        <th>
            @Html.ActionLink("Tilaus pvm", "Index", new { sortOrder = ViewBag.OrderDateSortParm, currentFilter1 = ViewBag.currentFilter1, currentShipperCategory = ViewBag.currentShipperCategory })@*(model => model.OrderDate)*@
        </th>
        <th>
            RequiredDate
        </th>
        <th>
            ShippedDate
        </th>
        <th>
            @Html.ActionLink("Rahtari", "Index", new { sortOrder = ViewBag.CompanyNameSortParm, currentFilter1 = ViewBag.currentFilter1, currentShipperCategory = ViewBag.currentShipperCategory })    @*@Html.DisplayNameFor(model => model.Shippers.CompanyName)*@
        </th>
        <th>
            Freight
        </th>
        <th>
            ShipName
        </th>
        <th>
            ShipAddress
        </th>
        <th>
            ShipCity
        </th>
        <th>
            ShipRegion
        </th>
        <th>
            Customers.CompanyName
        </th>
        <th>
            ShipPostalCode
        </th>
        <th>
            ShipCountry
        </th>
        <th>
            Employees.LastName
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td><button class="getOrderId fas fa-edit" data-orderid="@item.OrderID"></button><button class="delOrderId fas fa-trash-alt" data-orderid="@item.OrderID"></button></td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RequiredDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShippedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Shippers.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Freight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipRegion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipPostalCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipCountry)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customers.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employees.LastName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.OrderID }) |
                @Html.ActionLink("Details", "Details", new { id = item.OrderID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.OrderID })
            </td>
        </tr>
    }

</table>
@*Modal -tyyppisen ikkunan avauspainike*@
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#OrderEditModal">Avaa Modal-ikkuna</button>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter1 = ViewBag.currentFilter1, currentShipperCategory = ViewBag.currentShipperCategory }))

WebAppFirst/Views/Orders/_ModalCreate.cshtml
@model WebAppFirst.Models.Orders

@*Modal -tyyppisen ikkunan koodiesimerkki - modal koodi alkaa*@
<div class="modal fade" id="ModalOrderCreate">

    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Create order</h3>
            </div>
            <div class="modal-body">
                @*Modal -tyyppisen ikkunan koodiesimerkki - alkuperäisen lomakkeen koodi alkaa*@
                @using (Html.BeginForm("Create", "Orders", FormMethod.Post, new { id = "createForm" }))
                {
                    @Html.AntiForgeryToken()

                    <h4>Orders</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6">

                            <div class="form-group">
                                @Html.LabelFor(model => model.EmployeeID, "EmployeeID", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.RequiredDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.RequiredDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.RequiredDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShippedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShippedDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShippedDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipVia, "ShipVia", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("ShipVia", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ShipVia, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Freight, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Freight, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Freight, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>

                        <div class="col-sm-6">

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipAddress, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipAddress, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipCity, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipCity, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipCity, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipRegion, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipRegion, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipRegion, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipPostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipPostalCode, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipPostalCode, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipCountry, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipCountry, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipCountry, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <div>
                    @*Formin lähettävä button, joka ei kuitenkaan ole formin sisällä, mutta viittaa formin ID:hen*@
                    <button type="submit" class="btn btn-primary" form="createForm"><i class="fas fa-plus-square"></i></button>
                    @*Kontrollerin kutsu Url.Action -komennolla, jotta peruuttaminen johtaa alkutilanteeseen*@
                    <a href="@Url.Action("Index", "Orders")" class="btn btn-primary"><i class="fas fa-times"></i></a>
                </div>
            </div>

        </div>
    </div>
</div>